<?php
/**
 * Skills Page GitHub Profile README export.
 *
 * @package plainmark
 * @since 0.8.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Aggregate skills from posts and portfolio works.
 *
 * @return array<int,array{term:WP_Term,post_count:int,work_count:int,total:int}>
 */
function plainmark_aggregate_skills() {
	$technologies = get_terms(
		array(
			'taxonomy'   => 'technology',
			'hide_empty' => true,
			'orderby'    => 'count',
			'order'      => 'DESC',
		)
	);

	if ( is_wp_error( $technologies ) || empty( $technologies ) ) {
		return array();
	}

	global $wpdb;

	$term_ids     = array_map( 'absint', wp_list_pluck( $technologies, 'term_id' ) );
	$placeholders = implode( ',', array_fill( 0, count( $term_ids ), '%d' ) );

	// phpcs:ignore WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
	$counts_query = $wpdb->prepare(
		"SELECT tt.term_id, p.post_type, COUNT(*) AS cnt
		FROM {$wpdb->term_relationships} tr
		INNER JOIN {$wpdb->term_taxonomy} tt ON tr.term_taxonomy_id = tt.term_taxonomy_id
		INNER JOIN {$wpdb->posts} p ON tr.object_id = p.ID
		WHERE tt.taxonomy = 'technology'
		AND tt.term_id IN ({$placeholders})
		AND p.post_status = 'publish'
		AND p.post_type IN ('post', 'portfolio')
		GROUP BY tt.term_id, p.post_type",
		...$term_ids
	);

	$rows      = $wpdb->get_results( $counts_query ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
	$count_map = array();

	foreach ( $rows as $row ) {
		$term_id = (int) $row->term_id;
		if ( ! isset( $count_map[ $term_id ] ) ) {
			$count_map[ $term_id ] = array(
				'post'      => 0,
				'portfolio' => 0,
			);
		}
		$count_map[ $term_id ][ $row->post_type ] = (int) $row->cnt;
	}

	$skills = array();

	foreach ( $technologies as $term ) {
		$term_id    = (int) $term->term_id;
		$post_count = $count_map[ $term_id ]['post'] ?? 0;
		$work_count = $count_map[ $term_id ]['portfolio'] ?? 0;

		$skills[] = array(
			'term'       => $term,
			'post_count' => $post_count,
			'work_count' => $work_count,
			'total'      => $post_count + $work_count,
		);
	}

	usort(
		$skills,
		static function ( $a, $b ) {
			return $b['total'] <=> $a['total'];
		}
	);

	return $skills;
}

/**
 * Generate GitHub Profile README Markdown from skills.
 *
 * @return string Markdown string.
 */
function plainmark_generate_skills_readme() {
	$skills   = plainmark_aggregate_skills();
	$site_url = home_url();
	$name     = get_bloginfo( 'name' );
	$now      = wp_date( 'Y-m-d' );

	if ( empty( $skills ) ) {
		return '';
	}

	$markdown  = "## Tech Stack\n\n";
	$markdown .= "> Auto-generated from [{$name}]({$site_url}) - Last updated: {$now}\n\n";
	$markdown .= "### Skills\n\n";

	$badges = array();
	foreach ( $skills as $skill ) {
		$tech_name  = $skill['term']->name;
		$badge_name = rawurlencode( str_replace( ' ', '_', $tech_name ) );
		$badges[]   = "![{$tech_name}](https://img.shields.io/badge/{$badge_name}-informational?style=flat)";
	}

	$markdown .= implode( ' ', $badges ) . "\n\n";
	$markdown .= "### Output by Technology\n\n";
	$markdown .= "| Technology | Articles | Works | Total |\n";
	$markdown .= "|---|---|---|---|\n";

	foreach ( $skills as $skill ) {
		$term_link = get_term_link( $skill['term'] );
		$term_url  = is_wp_error( $term_link ) ? home_url( '/' ) : $term_link;
		$term_name = str_replace( '|', '\\|', $skill['term']->name );
		$markdown .= sprintf(
			"| [%s](%s) | %d | %d | %d |\n",
			$term_name,
			$term_url,
			(int) $skill['post_count'],
			(int) $skill['work_count'],
			(int) $skill['total']
		);
	}

	$markdown .= "\n---\n";
	$markdown .= "_Generated by [plainmark](https://github.com/masakiShito/plainmark)_\n";

	return $markdown;
}

/**
 * Handle the README download request.
 */
function plainmark_handle_skills_readme_download() {
	if ( ! isset( $_GET['plainmark_skills_export'] ) ) {
		return;
	}

	if ( 'readme' !== sanitize_key( wp_unslash( $_GET['plainmark_skills_export'] ) ) ) {
		return;
	}

	if ( ! is_user_logged_in() || ! current_user_can( 'edit_posts' ) ) {
		wp_die( esc_html__( '権限がありません。', 'plainmark' ) );
	}

	if ( ! isset( $_GET['_wpnonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ), 'plainmark_skills_export' ) ) {
		wp_die( esc_html__( 'セキュリティチェックに失敗しました。', 'plainmark' ) );
	}

	$markdown = plainmark_generate_skills_readme();

	if ( '' === $markdown ) {
		wp_die( esc_html__( 'スキルデータが見つかりません。', 'plainmark' ) );
	}

	$filename = 'skills-' . wp_date( 'Y-m-d' ) . '.md';

	header( 'Content-Type: text/markdown; charset=utf-8' );
	header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
	header( 'Cache-Control: no-cache, no-store, must-revalidate' );
	echo $markdown; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Markdown download.
	exit;
}
add_action( 'template_redirect', 'plainmark_handle_skills_readme_download' );

/**
 * Add export button to the Skills page.
 */
function plainmark_render_skills_export_button() {
	if ( ! current_user_can( 'edit_posts' ) ) {
		return;
	}

	$url = add_query_arg(
		array(
			'plainmark_skills_export' => 'readme',
			'_wpnonce'                => wp_create_nonce( 'plainmark_skills_export' ),
		),
		home_url( '/' )
	);

	printf(
		'<div class="skills-export"><a href="%1$s" class="button button-secondary">%2$s</a></div>',
		esc_url( $url ),
		esc_html__( 'GitHub README としてエクスポート', 'plainmark' )
	);
}
add_action( 'plainmark_after_skills_page_content', 'plainmark_render_skills_export_button' );
